# <span style="color:darkblue"> Lecture 2b: Subsetting Data </span>

<font size = "5">

In this lecture, we will work on subsetting data.

## <span style="color:darkblue"> I. Import Libraries and Read Files</span>

In [2]:
# the "pandas" library is for manipualting datasets
# the "matplotlib.pyplot" library is for creating graphs
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Read the car features dataset
carfeatures = pd.read_csv("data_raw/features.csv")

## <span style="color:darkblue"> II. Basic data display </span>

<font size = "5">

<font size = "5">

Display a dataset

- Remember that in VS-Code there is also a data viewer.
- Go to the variables tab at the top of the notebook

In [4]:
# The display() command will show the first 5 rows and the last five rows

display(carfeatures)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
1    15.0          8           350        165    3693          11.5  B-1689791
2    18.0          8           318        150    3436          11.0  P-1689802
3    16.0          8           304        150    3433          12.0  A-1689813
4    17.0          8           302        140    3449          10.5  F-1689824
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[398 rows x 7 columns]

<font size = "5" >

Extract column names

In [5]:
# Write the name of the dataset and use a period "." to extract 
# the attribute "columns" and the subttribute "values"

car_colnames = carfeatures.columns.values
print(car_colnames)

<ArrowStringArray>
[         'mpg',    'cylinders', 'displacement',   'horsepower',
       'weight', 'acceleration',   'vehicle_id']
Length: 7, dtype: str

<font size = "5">

Subset columns:

```python
data[list_names]
```

In [6]:
# To subset multiple columns write the name of the datasets 
# and enter a list in square brackets next to the name

list_subsetcols     = ["weight","mpg"]
subcols_carfeatures = carfeatures[list_subsetcols]
display(subcols_carfeatures)

# Or we can simply include the list directly inside square brackets
display(carfeatures[["weight","mpg"]])

     weight   mpg
0      3504  18.0
1      3693  15.0
2      3436  18.0
3      3433  16.0
4      3449  17.0
..      ...   ...
393    2790  27.0
394    2130  44.0
395    2295  32.0
396    2625  28.0
397    2720  31.0

[398 rows x 2 columns]

     weight   mpg
0      3504  18.0
1      3693  15.0
2      3436  18.0
3      3433  16.0
4      3449  17.0
..      ...   ...
393    2790  27.0
394    2130  44.0
395    2295  32.0
396    2625  28.0
397    2720  31.0

[398 rows x 2 columns]

<font size = "5">

Try it yourself!

- Extract the weight and acceleration variables

In [7]:
# Write your own code

# To subset multiple columns write the name of the datasets 
# and enter a list in square brackets next to the name

list_subsetcols     = ["weight","acceleration"]
subcols_carfeatures = carfeatures[list_subsetcols]
display(subcols_carfeatures)

     weight  acceleration
0      3504          12.0
1      3693          11.5
2      3436          11.0
3      3433          12.0
4      3449          10.5
..      ...           ...
393    2790          15.6
394    2130          24.6
395    2295          11.6
396    2625          18.6
397    2720          19.4

[398 rows x 2 columns]

## <span style="color:darkblue"> II. Queries </span>

<font size = "5">
Filter the data based on its content <br>

```python
data.query("logical expression")
```

<font size = "5">

(i) Expressions with colnames

In [8]:
# Enter any logical expression

data_threshold_mpg        = carfeatures.query("mpg >= 25")
data_rangeacceleration    = carfeatures.query("(acceleration >= 10) & (acceleration < 18)")

<font size = "5">

(ii) Expressions with colnames + global variables (@)

In [9]:
# You can invoke global variables into the query by using @variablename
# If you don't include @, then Python will try to look for a column with 
# that name and potentially throw an error.

threshold = 25
data_varthreshold_mpg = carfeatures.query("mpg >= @threshold")

<font size = "5">

(iii) Expressions with colnames with spaces

In [10]:
# Sometimes column names have spaces in them
# In this case use the "`" symbol, e.g.          `variable name`

carfeatures["new variable"] = carfeatures["mpg"]
data_spacesthreshold_mpg = carfeatures.query("`new variable` >= 25")

In [11]:
carfeatures["new variable two"] = carfeatures["mpg"]
data_spacesthreshold_mpg_two = carfeatures.query("`new variable two` >= 25")

<font size = "5">

Try it yourself!

-  Subset the data with mpg $\ge$ 25 and cylinders == 8

In [13]:
# Write your own code here

data_range_mpg_cylinders    = carfeatures.query("(mpg >= 25) & (cylinders == 8)")
display(data_range_mpg_cylinders)

,mpg,cylinders,displacement,horsepower,weight,acceleration,vehicle_id,new variable,new variable two
364,26.6,8,350,105,3725,19.0,O-1693784,26.6,26.6

## <span style="color:darkblue"> III. Subsetting by row/column position </span>

<font size = "5">

<font size = "5">

Sort by column

In [15]:
carsorted = carfeatures.sort_values(by = "mpg", ascending = False)
display(carsorted)

,mpg,cylinders,displacement,horsepower,weight,acceleration,vehicle_id,new variable,new variable two
322,46.6,4,86,65,2110,17.9,M-1693322,46.6,46.6
329,44.6,4,91,67,1850,13.8,H-1693399,44.6,44.6
325,44.3,4,90,48,2085,21.7,V-1693355,44.3,44.3
394,44.0,4,97,52,2130,24.6,V-1694114,44.0,44.0
326,43.4,4,90,48,2335,23.7,V-1693366,43.4,43.4
...,...,...,...,...,...,...,...,...,...
103,11.0,8,400,150,4997,14.0,C-1690913,11.0,11.0
67,11.0,8,429,208,4633,11.0,M-1690517,11.0,11.0
25,10.0,8,360,215,4615,14.0,F-1690055,10.0,10.0
26,10.0,8,307,200,4376,15.0,C-1690066,10.0,10.0
28,9.0,8,304,193,4732,18.5,H-1690088,9.0,9.0

<font size = "5">

Subset row(s)

``` data.iloc[ row_int , : ]``` $\quad$ or

``` data.iloc[ list_rows, : ]```

In [16]:
# The following command extracts all columns for row zero
# Remember that numbering starts at zero in Python
# In this case we will show the car with the highest "mpg" value

display(carsorted.iloc[0,:])
display(carsorted.iloc[[0,1,2],:])

mpg                      46.6
cylinders                   4
displacement               86
horsepower                 65
weight                   2110
acceleration             17.9
vehicle_id          M-1693322
new variable             46.6
new variable two         46.6
Name: 322, dtype: object

,mpg,cylinders,displacement,horsepower,weight,acceleration,vehicle_id,new variable,new variable two
322,46.6,4,86,65,2110,17.9,M-1693322,46.6,46.6
329,44.6,4,91,67,1850,13.8,H-1693399,44.6,44.6
325,44.3,4,90,48,2085,21.7,V-1693355,44.3,44.3

<font size = "5">

Subset block of rows

``` data.iloc[ lower:upper , : ]```

In [17]:
# Extract rows 0 to 5
display(carfeatures.iloc[0:5,:])

# Extract rows 8 onwards
display(carfeatures.iloc[ 8:, : ])

# Note: We can leave the numbers to the left and right of ":" blank
# in order to select all values before or after, respectively.

,mpg,cylinders,displacement,horsepower,weight,acceleration,vehicle_id,new variable,new variable two
0,18.0,8,307,130,3504,12.0,C-1689780,18.0,18.0
1,15.0,8,350,165,3693,11.5,B-1689791,15.0,15.0
2,18.0,8,318,150,3436,11.0,P-1689802,18.0,18.0
3,16.0,8,304,150,3433,12.0,A-1689813,16.0,16.0
4,17.0,8,302,140,3449,10.5,F-1689824,17.0,17.0

,mpg,cylinders,displacement,horsepower,weight,acceleration,vehicle_id,new variable,new variable two
8,14.0,8,455,225,4425,10.0,P-1689868,14.0,14.0
9,15.0,8,390,190,3850,8.5,A-1689879,15.0,15.0
10,15.0,8,383,170,3563,10.0,D-1689890,15.0,15.0
11,14.0,8,340,160,3609,8.0,P-1689901,14.0,14.0
12,15.0,8,400,150,3761,9.5,C-1689912,15.0,15.0
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,F-1694103,27.0,27.0
394,44.0,4,97,52,2130,24.6,V-1694114,44.0,44.0
395,32.0,4,135,84,2295,11.6,D-1694125,32.0,32.0
396,28.0,4,120,79,2625,18.6,F-1694136,28.0,28.0
397,31.0,4,119,82,2720,19.4,C-1694147,31.0,31.0

<font size = "5">

Similar for columns

- One column: $\quad$    ``` data.iloc[ : , col_integer ]```
- Multiple columns: $\quad$   ``` data.iloc[ : , list_cols ]```
- Row+Column: $\quad$ ``` data.iloc[ list_rows , list_cols ]```

<font size = "5">

Try it yourself!!

- Create a new datate called "car_ascendingmpg" which <br>
sorts cars from lowest to highest mpg
- Subset the data of 5 cars with the lowest "mpg"

HINT: Use ``sort_values(...,ascending = TRUE``)

In [ ]:
# Write your own code